let counter = 0;

let soups = [
    "Aguadito",
    "Ajiaco",
    "Açorda",
    "Acquacotta",
    "Amish preaching soup",
    "Analı kızlı soup",
    "Ant egg soup",
    "Ash-e doogh",
    "Aush, aash, āsh",
    "Avgolemono",
    "Avocado soup",
    "Bacon soup",
    "Bak kut teh",
    "Bakso",
    "Barley",
    "Batchoy",
    "Beef noodle soup",
    "Beer soup",
    "Bergen fish soup",
    "Bermuda fish chowder",
    "Bilo-bilo",
    "Binakol",
    "Binignit",
    "Bird's nest soup",
    "Black sesame soup",
    "Bob chorba",
    "Borscht/ Borshch",
    "Bouillabaisse",
    "Bouillon",
    "Bouneschlupp",
    "Bourou-Bourou",
    "Bread soup",
    "Brenebon",
    "Brown Windsor soup",
    "Bun bo Hue",
    "Buridda",
    "Butajiru (Tonjiru)",
    "Cabbage soup, kapusniak, kapustnica, zelnacka",
    "Caldillo de congrio",
    "Caldillo de perro",
    "Caldo verde",
    "Callaloo",
    "Canh chua",
    "Canja de Galinha",
    "Carp soup [cs]",
    "Carrot soup",
    "Cazuela",
    "Chestnut bisque",
    "Chicken noodle soup",
    "Chicken soup",
    "Chicken vegetable soup",
    "Chorba, shorba",
    "Chupe",
    "Chupe Andino",
    "Cioppino",
    "Cock-a-leekie",
    "Cold borscht / Šaltibarščiai",
    "Consommé",
    "Corn chowder",
    "Crab bisque",
    "Cream of apple soup",
    "Cream of asparagus",
    "Cream of broccoli",
    "Cream of celery",
    "Cream of chicken",
    "Cream of potato",
    "Cream of tomato",
    "Cream of Crab",
    "Cream of mushroom",
    "Crème Ninon",
    "Cucumber soup",
    "Cullen skink",
    "Curry Mee",
    "Dalithoy",
    "Dashi",
    "Dillegrout",
    "Dinengdeng",
    "Duck soup noodles",
    "Egg drop soup",
    "Egusi soup",
    "Ezogelin soup",
    "Escudella",
    "Fabada Asturiana",
    "Fanesca",
    "Fish soup bee hoon",
    "Fish",
    "Fisherman's Soup",
    "French onion soup",
    "Frittatensuppe",
    "Fruktsoppa",
    "Fufu and Egusi soup",
    "Fumet",
    "Garmugia",
    "Gazpacho",
    "Ginataan",
    "Ginestrata",
    "Gising-gising",
    "Goat meat pepper soup",
    "Gogi guksu",
    "Gomguk",
    "Goulash",
    "Ground nut soup",
    "Kimchi Guk",
    "Gumbo",
    "Harira",
    "Hot and sour soup",
    "Ikan kuah kuning",
    "Inubaran",
    "Íslensk Kjötsúpa",
    "Joumou",
    "Kadyos, baboy, kag langka",
    "Kadyos, manok, kag ubad",
    "Kharcho",
    "Kusksu",
    "Kwāti",
    "Laksa",
    "Lagman",
    "Leek soup",
    "Lettuce soup",
    "Lentil soup",
    "Linat-an",
    "Lobster stew",
    "Lobster bisque",
    "Log-log",
    "Lohikeitto",
    "Lung fung soup",
    "Lyvzha",
    "Maccu",
    "Maki mi",
    "Mami soup",
    "Manhattan clam chowder",
    "Marghi special",
    "Maryland crab soup",
    "Matzah ball soup",
    "Melon soup",
    "Minestrone",
    "Miso soup",
    "Miyeok guk",
    "Mohinga",
    "Mote de queso",
    "Mulligan Stew",
    "Mulligatawny",
    "Naengmyeon",
    "Nettle soup",
    "New England clam chowder",
    "Nikujaga",
    "Nilaga",
    "Odong",
    "Okra soup",
    "Okroshka",
    "Oxtail soup",
    "Palm nut soup",
    "Panada",
    "Panadelsuppe",
    "Pancit buko",
    "Pasta fagioli",
    "Yellow pea soup",
    "Peanut soup",
    "Philadelphia Pepper Pot",
    "Phở",
    "Pickle soup",
    "Pork blood soup",
    "Pozole",
    "Psarosoupa (ψαρόσουπα)",
    "Pumpkin",
    "Purée Mongole",
    "Ramen",
    "Rasam",
    "Rassolnik",
    "Rawon",
    "Rishtay / Rqaq o Adas",
    "Rose hip soup (Nyponsoppa)",
    "Rumford's Soup",
    "Saimin",
    "Salmorejo",
    "Sambar",
    "Samgyetang",
    "Sayur Asem",
    "Sayur Lodeh",
    "Scotch Broth",
    "Shark fin soup",
    "Shchav, sorrel soup, green borscht, green shchi",
    "Shchi",
    "Seafood chowder",
    "She-crab soup",
    "Shrimp bisque",
    "Sinabawang gulay",
    "Sinigang",
    "Sliced fish soup",
    "Snert",
    "Solyanka",
    "Sop saudara",
    "Sopa de Gato",
    "Sopas",
    "Soto",
    "Soto ayam",
    "Soup alla Canavese",
    "Soup No. 5",
    "Sour cherry soup",
    "Sour rye soup, white borscht, żur",
    "Sour soup (fish soup)",
    "Spinach soup",
    "Split pea",
    "Squash bisque",
    "Stone soup",
    "Stracciatella",
    "Sulu köfte",
    "Sup Kambing",
    "Suam na mais",
    "Taco soup",
    "Talabaw",
    "Talbina",
    "Tāng Fěn",
    "Tāng miǎn",
    "Tapado",
    "Tarator",
    "Tarhana",
    "Tekwan",
    "Tiger penis soup",
    "Tinola",
    "Tiyula itum",
    "Tom Yum",
    "Tomato bisque",
    "Tomato soup",
    "Tongseng",
    "Tortilla soup",
    "Tteokguk",
    "Turkey soup",
    "Ukha or yushka",
    "Vegetable soup",
    "Vichyssoise",
    "Vori vori",
    "Waterzooi",
    "Wedding soup",
    "Wine soup",
    "Winter melon",
    "Zuppa pavese",
]

document.querySelector(".counter").textContent = counter;

function incrementCounter() {
    counter++;
    document.querySelector(".counter").textContent = counter;
}

function addSoup() {
    const soup = soups[Math.floor(Math.random() * soups.length)];
    const soupElement = document.createElement("li");
    soupElement.textContent = soup;
    document.querySelector(".soups").appendChild(soupElement);
}

let soupHidden = false;
const soupElement = document.getElementsByClassName("soups")[0];

function hideSoup() {
    soupHidden = !soupHidden;
    if (soupHidden) {
        soupElement.style.display = "none";
    } else {
        soupElement.style.display = "block";
    }
}

const button = document.querySelector(".footer-button");
button.addEventListener("click", incrementCounter);

const button2 = document.querySelector(".content-button");
button2.addEventListener("click", addSoup);

const button3 = document.querySelector(".hide-button");
button3.addEventListener("click", hideSoup);
